<?php

namespace Swissup\SoldTogether\Console\Command;

use Magento\Framework\App;
use Symfony\Component\Console\Command\Command;
use Symfony\Component\Console\Input\InputInterface;
use Symfony\Component\Console\Output\OutputInterface;
use Symfony\Component\Console\Helper\ProgressBar;

abstract class AbstractReindexCommand extends Command
{
    /**
     * @var App\State
     */
    protected $state;

    /**
     * @var string
     */
    protected $relationName = 'Abstarct';

    /**
     * @var string
     */
    protected $objectName = 'abstract';

    /**
     * @var integer
     */
    protected $pageSize = 5;

    /**
     * Indexer object for soldtogether data
     */
    protected $indexer;

    /**
     * @param App\State $state
     */
    public function __construct(
        ?App\State $state = null
    ) {
        $this->state = $state ?: \Magento\Framework\App\ObjectManager::getInstance()
            ->get(App\State::class);
        parent::__construct();
    }

    /**
     * {@inheritdoc}
     */
    protected function configure()
    {
        $this->setName("swissup:soldtogether:{$this->objectName}:reindex")
            ->setDescription("Reindex \"{$this->relationName}\" relations.");
    }

    /**
     * {@inheritdoc}
     */
    protected function execute(InputInterface $input, OutputInterface $output)
    {
        $this->state->setAreaCode(App\Area::AREA_GLOBAL);
        // delete auto generated
        $output->writeln("Reindex \"{$this->relationName}\" relations.");
        $this->indexer->deleteAutogeneratedRelations();
        $output->writeln('Autogenerated relations cleared.');
        // prepare progress bar
        $count = $this->indexer->getItemsToProcessCount();
        $pageSize = $this->pageSize;
        $lastPage = $pageSize ? (ceil($count / $pageSize)) : 1;
        $progressBar = new ProgressBar($output, $count);
        $progressBar->setFormat("Indexing {$this->objectName}s - [%bar%] %percent:3s%%");
        $currPage = 0;
        do {
            $currPage++;
            $this->indexer->reindex($currPage, $pageSize);
            $progressBar->advance($pageSize);
        } while ($currPage < $lastPage);
        $output->write(PHP_EOL);
        // complete
        $output->writeln("Done. {$count} orders processed.");

        return 0;
    }
}
