<?php
// @codingStandardsIgnoreFile
/** @var $block \Swissup\SeoUrls\Block\Adminhtml\Attribute\Labels  */
?>
<style>
    .admin__scope-old #seourls-manage-labels-wrapper .col-store-view .input-text {
        width: 100%;
    }
</style>

<div class="fieldset-wrapper admin__collapsible-block-wrapper opened" id="seourls-manage-labels-wrapper">
    <div class="fieldset-wrapper-title">
        <strong class="admin__collapsible-title" data-toggle="collapse" data-target="#seourls-manage-labels-content">
            <span><?= /* @escapeNotVerified */ __('Manage In-URL Attribute Label') ?></span>
        </strong>
    </div>
    <div class="fieldset-wrapper-content in collapse" id="seourls-manage-labels-content">
        <p><?= /* @escapeNotVerified */ __('Use this section to set attribute labels for URLs in layered navigation.') ?></p>
        <fieldset class="admin__fieldset fieldset">
            <div class="admin__control-table-wrapper">
                <table class="admin__control-table" id="seourls-attribute-labels-table">
                    <thead>
                    <tr>
                        <?php foreach ($block->getStores() as $_store): ?>
                            <th class="col-store-view"><?= /* @escapeNotVerified */ $_store->getId() == \Magento\Store\Model\Store::DEFAULT_STORE_ID ? __('All Stores') : $_store->getName() ?></th>
                        <?php endforeach; ?>
                    </tr>
                    </thead>
                    <tbody>
                    <tr>
                        <?php $_labels = $block->getLabelValues() ?>
                        <?php foreach ($block->getStores() as $_store): ?>
                            <td class="col-store-view">
                                <input class="input-text" type="text" name="swissup[seourl_label][<?= /* @escapeNotVerified */ $_store->getId() ?>]" value="<?= $block->escapeHtml($_labels[$_store->getId()]) ?>"<?php if ($block->getReadOnly()):?> disabled="disabled"<?php endif;?>/>
                            </td>
                        <?php endforeach; ?>
                    </tr>
                    </tbody>
                </table>
            </div>
        </fieldset>
    </div>
</div>
