<?php
// @codingStandardsIgnoreFile
/** @var $block \Swissup\SeoUrls\Block\Adminhtml\Attribute\Options */
?>
<?php
    $optionValues = $block->getOptionValues();
    if (!$optionValues) {
        return;
    }

    $stores = $block->getStores();
?>
<style>
    .admin__scope-old #seourls-manage-options-panel .input-text {
        width: 100%;
    }
</style>
<div class="fieldset-wrapper admin__collapsible-block-wrapper opened" id="seourls-manage-options-wrapper">
    <div class="fieldset-wrapper-title">
        <strong class="admin__collapsible-title" data-toggle="collapse" data-target="#seourls-manage-options-content">
            <span><?= /* @escapeNotVerified */ __('Manage In-URL Option Label for Attribute') ?></span>
        </strong>
    </div>
    <div class="fieldset-wrapper-content in collapse" id="seourls-manage-options-content">
        <p><?= /* @escapeNotVerified */ __('Use this section to set attribute values for URLs in layered navigation.') ?></p>
        <fieldset class="admin__fieldset fieldset">
            <div class="admin__control-table-wrapper" id="seourls-manage-options-panel" data-index="attribute_options_select_container">
                <table class="admin__control-table" data-index="attribute_options_select">
                    <thead>
                        <tr id="seourls-attribute-options-table">
                            <th class="col-default control-table-actions-th">
                                <span><?= __('Option') ?></span>
                            </th>
                            <?php
                            foreach ($stores as $_store): ?>
                                <th>
                                    <span><?= /* @escapeNotVerified */ $_store->getId() == \Magento\Store\Model\Store::DEFAULT_STORE_ID ? __('All Stores') : $_store->getName() ?></span>
                                </th>
                            <?php endforeach;
                            $storetotal = count($stores) + 1;
                            ?>
                        </tr>
                    </thead>
                    <tbody data-role="options-container" class="ignore-validate"></tbody>
                    <tfoot>
                    <tr>
                        <th colspan="<?= (int)$storetotal ?>" class="validation">
                            <!-- <input type="hidden" class="required-dropdown-attribute-entry" name="seourls_attribute_validation"/> -->
                            <!-- <input type="hidden" class="required-dropdown-attribute-unique" name="seourls_attribute_validation_unique"/> -->
                        </th>
                    </tr>
                    </tfoot>
                </table>
                <input type="hidden" id="seourls-option-count-check" value="" />
            </div>
        </fieldset>
    </div>
</div>
<script id="seourls-option-template" type="text/x-magento-template">
    <tr <% if (data.rowClasses) { %>class="<%- data.rowClasses %>"<% } %>>
        <td class="col-default">
            <input name="swissup[original_value][<%- data.id %>]" value="<%- data.id %>" type="hidden" />
            <input value="<%- data.optionLabel %>" type="text" readonly />
        </td>
        <?php foreach ($stores as $_store): ?>
        <td class="col-<%- data.id %>"><input name="swissup[seourl_value][<%- data.id %>][<?= (int) $_store->getId() ?>]" value="<%- data.store<?= /* @noEscape */ (int) $_store->getId() ?> %>" class="input-text<?php if ($_store->getId() == \Magento\Store\Model\Store::DEFAULT_STORE_ID): ?> required-option required-unique<?php endif; ?>" type="text" /></td>
        <?php endforeach; ?>
    </tr>
</script>
<?php
$values = [];
foreach($block->getOptionValues() as $value) {
    $value = $value->getData();
    $values[] = is_array($value) ? array_map(function($str) {
        return htmlspecialchars_decode((string)$str, ENT_QUOTES);
    }, $value) : $value;
}
?>
<script type="text/x-magento-init">
    {
        "#seourls-manage-options-panel": {
            "Swissup_SeoUrls/js/options": {
                "attributesData": <?= /* @noEscape */ json_encode($values, JSON_HEX_QUOT) ?>,
                "attributeTemplate": "#seourls-option-template"
            }
        }
    }
</script>
