<!doctype html>
<html amp <?= $htmlAttributes ?>>
<head>
<?php
    // stop newrelic from injecting custom javascript
    if (extension_loaded('newrelic')) {
        newrelic_disable_autorum();
    }
?>
<meta charset="utf-8">
<script async src="https://cdn.ampproject.org/v0.js"></script>
<script async custom-element="amp-sidebar" src="https://cdn.ampproject.org/v0/amp-sidebar-0.1.js"></script>
<script async custom-element="amp-accordion" src="https://cdn.ampproject.org/v0/amp-accordion-0.1.js"></script>
<script async custom-element="amp-lightbox" src="https://cdn.ampproject.org/v0/amp-lightbox-0.1.js"></script>
<script async custom-element="amp-list" src="https://cdn.ampproject.org/v0/amp-list-0.1.js"></script>
<script async custom-template="amp-mustache" src="https://cdn.ampproject.org/v0/amp-mustache-0.2.js"></script>
<meta name="amp-scripts">
<?= $this->pageConfigRenderer->renderTitle() ?>
<meta name="viewport" content="width=device-width,minimum-scale=1,initial-scale=1">
<meta name="description" content="<?= htmlspecialchars((string)$this->getConfig()->getDescription()) ?>">
<meta name="keywords" content="<?= htmlspecialchars((string)$this->getConfig()->getKeywords()) ?>">
<meta name="robots" content="<?= htmlspecialchars((string)$this->getConfig()->getRobots()) ?>">
<?php $favIconUrl = $this->pageConfig->getFaviconFile() ?: $this->pageConfig->getDefaultFavicon();
if (!filter_var($favIconUrl, FILTER_VALIDATE_URL)):
  $favIconUrl = $this->getViewFileUrl($favIconUrl);
endif; ?>
<link rel="icon" href="<?= $favIconUrl ?>" type="image/x-icon">
<link rel="shortcut icon" href="<?= $favIconUrl ?>" type="image/x-icon">
<link rel="canonical" href="<?= $this->urlBuilder->getUrl('*/*/*', ['_use_rewrite' => true, '_query' => ['amp' => null]]) ?>">
<style amp-custom></style>
<style amp-boilerplate>body{-webkit-animation:-amp-start 8s steps(1,end) 0s 1 normal both;-moz-animation:-amp-start 8s steps(1,end) 0s 1 normal both;-ms-animation:-amp-start 8s steps(1,end) 0s 1 normal both;animation:-amp-start 8s steps(1,end) 0s 1 normal both}@-webkit-keyframes -amp-start{from{visibility:hidden}to{visibility:visible}}@-moz-keyframes -amp-start{from{visibility:hidden}to{visibility:visible}}@-ms-keyframes -amp-start{from{visibility:hidden}to{visibility:visible}}@-o-keyframes -amp-start{from{visibility:hidden}to{visibility:visible}}@keyframes -amp-start{from{visibility:hidden}to{visibility:visible}}</style><noscript><style amp-boilerplate>body{-webkit-animation:none;-moz-animation:none;-ms-animation:none;animation:none}</style></noscript>
</head>
<body <?= $bodyAttributes ?>>
<?= $layoutContent ?>
</body>
</html>
