<?php
    $helper = $this->helper(\Magento\Search\Helper\Data::class);
?>
<amp-lightbox id="search-lightbox" layout="nodisplay">
    <div class="lightbox">
        <div class="block block-search">
            <div class="block block-title"><strong><?= /* @escapeNotVerified */ __('Search') ?></strong></div>
            <div class="block block-content">
                <form class="form minisearch" id="search_mini_form" action="<?= /* @escapeNotVerified */ $helper->getResultUrl() ?>" method="get">
                    <div class="field search">
                        <label class="label" for="search" data-role="minisearch-label">
                            <span><?= /* @escapeNotVerified */ __('Search') ?></span>
                        </label>
                        <div class="control">
                            <input id="search"
                                type="text"
                                name="<?= /* @escapeNotVerified */ $helper->getQueryParamName() ?>"
                                value="<?= /* @escapeNotVerified */ $helper->getEscapedQueryText() ?>"
                                placeholder="<?= /* @escapeNotVerified */ __('Search entire store here...') ?>"
                                class="input-text"
                                maxlength="<?= /* @escapeNotVerified */ $helper->getMaxQueryLength() ?>"
                                role="combobox"
                                aria-haspopup="false"
                                aria-autocomplete="both"
                                autocomplete="off"/>
                            <?= $block->getChildHtml() ?>
                        </div>
                    </div>
                    <div class="actions">
                        <button type="submit"
                                title="<?= $block->escapeHtml(__('Search')) ?>"
                                class="action search">
                            <span><?= /* @escapeNotVerified */ __('Search') ?></span>
                        </button>
                    </div>
                </form>
            </div>
        </div>
        <button class="close close-icon" on="tap:search-lightbox.close"></button>
    </div>
</amp-lightbox>
