<?php

namespace Swissup\SoldTogether\Model\ResourceModel;

use Magento\Framework\Model\ResourceModel\Db\AbstractDb;
use Magento\Framework\DB\Select;
use Magento\Framework\DB\Adapter\AdapterInterface;

abstract class AbstractResourceModel extends AbstractDb
{
    /**
     * Check DB table if there duplicated relations
     *
     * @return boolean
     */
    public function isCondenseDataRequired()
    {
        $select = $this->getCondenseDataSelect();
        $select->reset(Select::COLUMNS)
            ->columns(['count' => 'count(1)'])
            ->having('count > 1');
        return (bool)$this->getConnection()->fetchRow($select);
    }

    /**
     * Prepare select to get condensed data (duplicated relations removed)
     *
     * @return Select
     */
    protected function getCondenseDataSelect()
    {
        $select = $this->getConnection()->select()->from(
            $this->getMainTable(),
            [
                'product_id',
                'related_id',
                'store_id',
                'weight' => 'max(weight)',
                'is_admin' => 'max(is_admin)'
            ]
        )
        ->group(['product_id', 'related_id', 'store_id']);

        return $select;
    }

    /**
     * Execute relations data condense
     *
     * @return void
     */
    public function condenseData()
    {
        // find last relation ID
        $select = $this->getConnection()->select()->from(
            $this->getMainTable(),
            ['relation_id' => 'max(relation_id)']
        );
        $data = $this->getConnection()->fetchRow($select);
        if (!$data || !isset($data['relation_id'])) {
            return;
        }

        $lastOldDataId = $data['relation_id'];
        // preapre insert into table query
        $columns = [
            'product_id',
            'related_id',
            'store_id',
            'weight',
            'is_admin'
        ];
        $query = sprintf(
            'INSERT INTO %s(%s) %s',
            $this->getMainTable(),
            implode(', ', $columns),
            (string)$this->getCondenseDataSelect()
        );
        // execute insert query
        $this->getConnection()->query($query);
        // delete old data
        $this->getConnection()->delete(
            $this->getMainTable(),
            ['relation_id <= ?' => $lastOldDataId]
        );
    }

    /**
     * Delete auto generated relations
     *
     * @return void
     */
    public function deleteAutogeneratedRelations()
    {
        $connection = $this->getConnection();
        $connection->delete(
            $this->getMainTable(),
            ['is_admin=?' => 0]
        );
    }

    /**
     * {@inheritdocs}
     */
    protected function _getLoadSelect($field, $value, $object)
    {
        $select = parent::_getLoadSelect($field, $value, $object);
        if ($field == 'product_id') {
            foreach (['related_id', 'store_id'] as $f) {
                if ($object->hasData($f)) {
                    $v = $object->getData($f);
                    $f = $this->getConnection()->quoteIdentifier(
                        sprintf('%s.%s', $this->getMainTable(), $f)
                    );
                    $select->where($f . '=?', $v);
                }
            }
        }

        return $select;
    }

    public function readLinkedData(
        $productId,
        array $columns = ['related_id', 'weight']
    ): array {
        $connection = $this->getConnection();
        $select = $connection->select()->from(
                $this->getMainTable(),
                $columns
            );
        if (is_array($productId)) {
            $select->where('product_id IN (?)', $productId);
        } else {
            $select->where('product_id = ?', $productId);
        }

        return $connection->fetchAssoc($select);
    }

    public function saveLinkedData(
        $productId,
        array $newData
    ) {
        $connection = $this->getConnection();
        $columns = ['related_id', 'weight', 'relation_id'];
        $isDataSerializedExists = $connection->tableColumnExists(
            $this->getMainTable(),
            'data_serialized'
        );
        if ($isDataSerializedExists) {
            $columns[] = 'data_serialized';
        }
        $dbData = $this->readLinkedData($productId, $columns);

        $rowsToDelete = array_diff_key($dbData, $newData);
        $rowsToInsert = array_diff_key($newData, $dbData);
        $rowsToUpdate = array_intersect_key($newData, $dbData);

        if ($rowsToDelete) {
            $idsToDelete = array_map(function ($item) {
                return $item['relation_id'];
            }, $rowsToDelete);
            $connection->delete(
                $this->getMainTable(),
                ['relation_id IN (?)' => $idsToDelete]
            );
        }

        $dataToReplace = [];
        foreach ($rowsToInsert as $relatedId => $row) {
            $item = [
                null, // relation_id
                $productId, // product_id
                $relatedId, // related_id
                '0', // store_id
                $row['weight'] ?? '0', // weight
                '1' // is_admin
            ];
            if ($isDataSerializedExists) {
                $serialize = $row;
                unset($serialize['weight']);
                $serialize = array_filter($serialize);
                $item[] = $this->getSerializer()
                    ->serialize($serialize ?: $this->getSerializeDefault('data_serialized'));
            }

            $dataToReplace[] = $item;
        }

        foreach ($rowsToUpdate as $relatedId => $row) {
            $dbItem = $dbData[$relatedId];
            $isUpdateRequired = false;
            $item = [
                $dbItem['relation_id'], // relation_id
                $productId, // product_id,
                $relatedId, // related_id,
                '0', // store_id
                $row['weight'] ?? '0', // weight
                '1' // is_admin
            ];
            $isUpdateRequired = (($row['weight'] ?? '0') != $dbItem['weight']);

            if ($isDataSerializedExists) {
                $newSerialize = $row;
                unset($newSerialize['weight']);
                $newSerialize = array_filter($newSerialize);
                list($serializeDefault, $unserializeDefault) = $this->_serializableFields['data_serialized'];
                if (empty($dbItem['data_serialized'])) {
                    $dbSerialize = $unserializeDefault;
                } else {
                    $dbSerialize = $this->getSerializer()->unserialize($dbItem['data_serialized']);
                    $dbSerialize = $dbSerialize ?: $unserializeDefault;
                }

                foreach ($newSerialize as $key => $newValue) {
                    if (!isset($dbSerialize[$key])
                        || $newValue != $dbSerialize[$key]
                    ) {
                        $isUpdateRequired = true;
                    }
                }

                if (array_diff_key($dbSerialize ?: [], $newSerialize)) {
                    $isUpdateRequired = true;
                }

                $serialize = $newSerialize ?: [];
                $item[] = $this->getSerializer()->serialize($serialize ?: $serializeDefault);
            }

            if ($isUpdateRequired) {
                $dataToReplace[] = $item;
            }
        }

        if ($dataToReplace) {
            $columns = ['relation_id', 'product_id', 'related_id', 'store_id', 'weight', 'is_admin'];
            if ($isDataSerializedExists) {
                $columns[] = 'data_serialized';
            }

            $connection->insertArray(
                $this->getMainTable(),
                $columns,
                $dataToReplace,
                AdapterInterface::REPLACE
            );
        }
    }

    public function updateLinkedData(
        array $newData
    ) {
        $connection = $this->getConnection();
        $columns = ['relation_id', 'product_id', 'related_id', 'store_id', 'weight', 'is_admin'];
        $isDataSerializedExists = $connection->tableColumnExists(
            $this->getMainTable(),
            'data_serialized'
        );

        if ($isDataSerializedExists) {
            $columns[] = 'data_serialized';
        }

        $productIds = array_reduce($newData, function ($productIds, $row) {
            if (!in_array($row['product_id'], $productIds)) {
                $productIds[] = $row['product_id'];
            }

            return $productIds;
        }, []);

        $dbData = $this->readLinkedData($productIds, $columns);
        $dataToReplace = [];
        foreach ($newData as $row) {
            $dbItem = [];
            foreach ($dbData as $dbRow) {
                if (($dbRow['product_id'] == $row['product_id'])
                && ($dbRow['related_id'] == $row['related_id'])) {
                    $dbItem = $dbRow;
                }
            }

            if (empty($dbItem)) {
                // DB row not found - add new relation
                $itemToReplace = [
                    null, // relation_id
                    $row['product_id'], // product_id
                    $row['related_id'], // related_id
                    $row['store_id'], // store_id
                    $row['weight'] ?? '0', // weight
                    $row['is_admin'] // is_admin
                ];
                if ($isDataSerializedExists) {
                    $itemToReplace[] = $this->getSerializeDefault('data_serialized');
                }
            } else {
                $itemToReplace = $dbItem;
                $itemToReplace['weight'] = $dbItem['weight'] + $row['weight'];
            }

            $dataToReplace[] = $itemToReplace;
        }

        if (!empty($dataToReplace)) {
            $connection->insertArray(
                $this->getMainTable(),
                $columns,
                $dataToReplace,
                AdapterInterface::REPLACE
            );
        }
    }

    private function getSerializeDefault($fieldName) {
        list($serializeDefault, $unserializeDefault) = $this->_serializableFields[$fieldName];

        return $serializeDefault;
    }
}
