<?php
    $mode = $block->getRequest()->getParam('mode');
    $oppositeSide = $block->getSide() == 'left' ? 'right' : 'left';
    $width = $mode == 'category' ? '8px' : '15px';
    $halfHeight = $mode == 'category' ? '15px' : '25px';
?>
<span style="padding-<?= $oppositeSide ?>: <?= $mode == 'category' ? '5px' : '10px' ?>">
<?= $this->helper(\Swissup\ProLabels\Helper\Preset::class)->getLabelText(); ?>
</span>
<b style="height: 0; width: 0; <?= $oppositeSide ?>: -<?= $width ?>; border-top: <?= $halfHeight ?> solid <?= $block->getBackgroundColor() ?>; border-bottom: <?= $halfHeight ?> solid <?= $block->getBackgroundColor() ?>; border-<?= $oppositeSide ?>: <?= $width ?> solid transparent; position: absolute;">
