<?php
    $mode = $block->getRequest()->getParam('mode');
    $oppositeSide = $block->getSide() == 'left' ? 'right' : 'left';
    $height = $mode == 'category' ? '30px' : '50px';
?>
background: <?= $block->getBackgroundColor() ?>;
color: #fff;
font-family: 'Ubuntu', sans-serif;
font-size: <?= $mode == 'category' ? '12px' : '14px' ?>;
height: <?= $height ?>;
<?= $block->getSide() ?>: -1px;
line-height: <?= $height ?>;
margin: <?= $mode == 'category' ? '5px 0' : '10px 0' ?>;
margin-<?= $oppositeSide ?>: <?= $mode == 'category' ? '8px' : '15px' ?>;
padding: <?= $mode == 'category' ? '0 2px' : '0 5px' ?>;
padding-<?= $block->getSide() ?>: <?= $mode == 'category' ? '8px' : '15px' ?>;
text-shadow: 0 1px 0 rgba(0,0,0,0.3);
white-space: nowrap;
