<script type="text/x-magento-init">
{
    ".swissup-seosuite-tab": {
        "Swissup_Core/js/system-config/section-mover": {
            "destination": ".section-config.swissup-seomodules-container",
            "itemToActivateWhenSelected": ".swissup-seosuite-config-item",
            "title": {
                "selected": "<?= $block->escapeJs(__('SEO Suite module: <strong>{{itemName}}</strong> <small><a href="#">Change</a></small>')) ?>",
                "no": "<?= $block->escapeJs(__('Please select SEO Suite module')) ?>"
            }
        }
    }
}
</script>