<?php
/**
 * Product list actions template
 *
 * @var $block \Magento\Framework\View\Element\Template
 * @var \Magento\Framework\Escaper $escaper
 * @var \Magento\Framework\View\Helper\SecureHtmlRenderer $secureRenderer
 */
?>
<?php
    use Magento\Framework\App\Action\Action;

    $parentBlock = $this->getParentBlock();
    $_product = $this->getProduct();
    $position = $this->getPosition();
    $pos = (string) $parentBlock->getPositioned();
    $viewMode = (string) $parentBlock->getMode();
    $options = [];
?>

<div class="product actions product-item-actions">
    <div class="actions-primary">
        <?php if ($_product->isSaleable()):?>
            <?php $postParams = $parentBlock->getAddToCartPostParams($_product); ?>
            <form data-role="tocart-form"
                  data-product-sku="<?= $escaper->escapeHtml($_product->getSku()) ?>"
                  action="<?= $escaper->escapeUrl($postParams['action']) ?>"
                  data-mage-init='{"catalogAddToCart": {}}'
                  method="post">
                <?php if ($parentBlock->getData('viewModel')) {
                    $options = $parentBlock->getData('viewModel')->getOptionsData($_product);
                } ?>
                <?php foreach ($options as $optionItem): ?>
                    <input type="hidden"
                           name="<?= $escaper->escapeHtml($optionItem['name']) ?>"
                           value="<?= $escaper->escapeHtml($optionItem['value']) ?>">
                <?php endforeach; ?>
                <input type="hidden"
                       name="product"
                       value="<?= /* @noEscape */ $postParams['data']['product'] ?>">
                <input type="hidden"
                       name="<?= /* @noEscape */ Action::PARAM_NAME_URL_ENCODED ?>"
                       value="<?=
                       /* @noEscape */ $postParams['data'][Action::PARAM_NAME_URL_ENCODED]
                        ?>">
                <?= $parentBlock->getBlockHtml('formkey') ?>
                <button type="submit"
                        title="<?= $escaper->escapeHtmlAttr(__('Add to Cart')) ?>"
                        class="action tocart primary"
                        disabled>
                    <span><?= $escaper->escapeHtml(__('Add to Cart')) ?></span>
                </button>
            </form>
        <?php else:?>
            <?php if ($_product->isAvailable()):?>
                <div class="stock available">
                    <span><?= $escaper->escapeHtml(__('In stock')) ?></span></div>
            <?php else:?>
                <div class="stock unavailable">
                    <span><?= $escaper->escapeHtml(__('Out of stock')) ?></span></div>
            <?php endif; ?>
        <?php endif; ?>
    </div>
    <?= ($pos && strpos($pos, $viewMode . '-primary')) ?
        /* @noEscape */ $secureRenderer->renderStyleAsTag(
            $position,
            'product-item-info_' . $_product->getId() . ' div.actions-primary'
        ) : '' ?>
    <div data-role="add-to-links" class="actions-secondary">
        <?php if ($addToBlock = $parentBlock->getChildBlock('addto')): ?>
            <?= $addToBlock->setProduct($_product)->getChildHtml() ?>
        <?php elseif (!$parentBlock->getData('viewModel')): // CatalogWidget ?>
            <?php if ($this->helper(\Magento\Wishlist\Helper\Data::class)->isAllow()): ?>
                <a href="#"
                   data-post='<?= /* @noEscape */ $block->getAddToWishlistParams($_product) ?>'
                   class="action towishlist"
                   data-action="add-to-wishlist"
                   title="<?= $block->escapeHtmlAttr(__('Add to Wish List')) ?>">
                    <span><?= $escaper->escapeHtml(__('Add to Wish List')) ?></span>
                </a>
            <?php endif; ?>
            <?php if ($parentBlock->getAddToCompareUrl()): ?>
                <?php $compareHelper = $this->helper(\Magento\Catalog\Helper\Product\Compare::class);?>
                <a href="#"
                    class="action tocompare"
                    data-post='<?= /* @noEscape */ $compareHelper->getPostDataParams($_product) ?>'
                    title="<?= $block->escapeHtmlAttr(__('Add to Compare')) ?>">
                    <span><?= $escaper->escapeHtml(__('Add to Compare')) ?></span>
                </a>
            <?php endif; ?>
        <?php endif ?>
    </div>
    <?= ($pos && strpos($pos, $viewMode . '-secondary')) ?
        /* @noEscape */ $secureRenderer->renderStyleAsTag(
            $position,
            'product-item-info_' . $_product->getId() . ' div.actions-secondary'
        ) : '' ?>
</div>
