<?php
    if (!$slider = $block->getSlider()) return;
    $slides = $slider->getSlides();
    if (count($slides) < 1) return;

    // detect slider width and height by first slide size
    $ampImageHelper = $this->helper('Swissup\Amp\Helper\Image');
    $firstSlideImage = $block->getImageRenderer()->getImageUrl($slides[0]['image']);
    $width  = $ampImageHelper->getWidth($firstSlideImage);
    $height = $ampImageHelper->getHeight($firstSlideImage);
    $sliderHtmlId = "easyslide-{$slider->getIdentifier()}";

    $autoplay = $slider->getData('autoplay');
    $thumbClass = $slider->getData('thumbs') ? " easyslide-wrapper-thumbs-{$slider->getData('thumbs_position')}" : '';
?>
<div class="easyslide-wrapper<?= $block->escapeHtmlAttr($thumbClass) ?>">
    <amp-carousel class="easyslide"
        width="<?= $block->escapeHtmlAttr($width) ?>"
        height="<?= $block->escapeHtmlAttr($height) ?>"
        id="<?= $block->escapeHtmlAttr($sliderHtmlId) ?>"
        type="slides" loop
        <?php if ($autoplay) : ?>
            autoplay delay="<?= $block->escapeHtmlAttr($autoplay) ?>"
        <?php endif ?>
        layout="responsive">
        <?php foreach ($slides as $slide): ?>
            <div class="swiper-slide">
                <?php if ($slide['url']) : ?>
                    <a href="<?= $block->escapeUrl($slide['url']) ?>" class="easyslide-link">
                <?php endif ?>
                        <?= /* @noEscape */ $block->getImageRenderer()->render($slide, $slider->getSizes(), false); ?>
                <?php if ($slide['url']) : ?>
                    </a>
                <?php endif ?>

                <?php if (!empty($slide['description'])) : ?>
                    <?php $className = implode(' ', [
                        'easyslide-description',
                        "easyslide-description-{$slide['desc_position']}",
                        "easyslide-background-{$slide['desc_background']}"
                    ]) ?>
                    <div class="<?= $block->escapeHtmlAttr($className) ?>">
                        <?= /* @noEscape */ $block->getSlideDescription($slide['description']) ?>
                    </div>
                <?php endif; ?>
            </div>
        <?php endforeach; ?>
    </amp-carousel>
<?php if ($slider->getData('thumbs')): ?>
    <?= /* @noEscape */ $block->fetchView($block->getTemplateFile('swissupamp/thumbs.phtml')) ?>
<?php endif ?>
</div>
