<?php
namespace Swissup\SoldTogether\Controller\Adminhtml\Order;

use Magento\Backend\App\Action\Context;

class Reindex extends \Magento\Backend\App\Action
{
    /**
     * Prefix for data in backend session
     *
     * @var string
     */
    protected $_dataPrefix = "swissup_soldtogether_order";
    /**
     * Size of step in data processing
     *
     * @var integer
     */
    protected $_stepSize = 10;
    /**
     * Message on processing complete
     *
     * @var string
     */
    protected $_completeMessage = "All Orders have been indexed.";

    /**
     * @var \Magento\Framework\Controller\Result\JsonFactory
     */
    protected $resultJsonFactory;

    /**
     * @param \Magento\Framework\Controller\Result\JsonFactory $resultJsonFactory
     * @param Context $context
     */
    public function __construct(
        \Magento\Framework\Controller\Result\JsonFactory $resultJsonFactory,
        Context $context
    ) {
        $this->resultJsonFactory = $resultJsonFactory;
        parent::__construct($context);
    }

    /**
     * Reindex orders action
     *
     * @throws \Zend_Db_Statement_Exception
     */
    public function execute()
    {
        $step = $this->_request->getParam('step', null);
        if (is_null($step)) {
            $this->getIndexerModel()->deleteAutogeneratedRelations();
            $step = 1;
        }

        $count = $this->_request->getParam('count', null);
        if (is_null($count)) {
            $count = $this->getIndexerModel()->getItemsToProcessCount();
        }

        if ($count < 1) {
            $this->messageManager->addNotice(__("We couldn't find data to process"));

            $response = [
                'finished'  => true
            ];
        } else {
            $this->getIndexerModel()->reindex($step, $this->_stepSize);
            if (($step * $this->_stepSize) > $count) {
                $this->messageManager->addSuccess(__($this->_completeMessage));

                $response = [
                    'finished' => true
                ];
            } else {
                $percent = 100 * $step * $this->_stepSize / $count;
                $responseLoaderText = ($step * $this->_stepSize) . ' of ' . $count . ' - '
                    . (int)$percent . '%';
                $response = [
                    'nextStep' => $step + 1,
                    'count' => $count,
                    'finished'  => false,
                    'loaderText' => $responseLoaderText
                ];
            }
        }

        /** @var \Magento\Framework\Controller\Result\Json $resultJson */
        $resultJson = $this->resultJsonFactory->create();

        return $resultJson->setData($response);
    }

    protected function getIndexerModel()
    {
        return $this->_objectManager
            ->get('Swissup\SoldTogether\Model\OrderIndexer');
    }
}
