<?php
/* @var $block \Magento\Catalog\Block\Product\Compare\ListCompare */
?>
<?php $total = $block->getItems()->getSize() ?>
<?php if ($total): ?>
    <?php $ampHelper = $this->helper('Swissup\Amp\Helper\Catalog'); ?>
    <div class="table-wrapper comparison">
        <table class="data table table-comparison" id="product-comparison">
            <thead>
            <tr>
                <?php $index = 0 ?>
                <?php foreach ($block->getItems() as $item): ?>
                    <?php if ($index++ == 0): ?>
                        <th scope="row" class="cell label remove"><span><?= /* @escapeNotVerified */ __('Remove Product') ?></span></th>
                    <?php endif; ?>
                    <td class="cell remove product">
                        <?php $removeUrl = $block->getUrl(
                            'catalog/product_compare/remove',
                            ['product' => $item->getId()]
                        ); ?>
                        <form method="post" action="<?= $removeUrl ?>">
                            <button type="submit" title="<?= $block->escapeHtml(__('Remove Product')) ?>" class="action delete">
                                <span><?= $block->escapeHtml(__('Remove Product')) ?></span>
                            </button>
                        </form>
                    </td>
                <?php endforeach; ?>
            </tr>
            </thead>
            <tbody>
            <tr>
                <?php $index = 0; ?>
                <?php $helper = $this->helper('Magento\Catalog\Helper\Output'); ?>
                <?php /** @var $item \Magento\Catalog\Model\Product */ ?>
                <?php foreach ($block->getItems() as $item): ?>
                    <?php if ($index++ == 0): ?>
                        <th scope="row" class="cell label product"><span><?= /* @escapeNotVerified */ __('Product') ?></span></th>
                    <?php endif; ?>
                    <td data-th="<?= $block->escapeHtml(__('Product')) ?>" class="cell product info">
                        <a class="product-item-photo" href="<?= /* @escapeNotVerified */ $block->getProductUrl($item) ?>" title="<?= /* @escapeNotVerified */ $block->stripTags($item->getName(), null, true) ?>">
                            <?= $block->getImage($item, 'product_comparison_list')->toHtml() ?>
                        </a>
                        <strong class="product-item-name">
                            <a href="<?= /* @escapeNotVerified */ $block->getProductUrl($item) ?>" title="<?= /* @escapeNotVerified */ $block->stripTags($item->getName(), null, true) ?>">
                                <?= /* @escapeNotVerified */ $helper->productAttribute($item, $item->getName(), 'name') ?>
                            </a>
                        </strong>
                        <?= /* @escapeNotVerified */ $block->getProductPrice($item, '-compare-list-top') ?>
                        <div class="product-item-actions">
                            <div class="actions-primary">
                                <?php if ($item->isSaleable()): ?>
                                    <form data-role="tocart-form" action="<?= /* @escapeNotVerified */ $block->getAddToCartUrl($item) ?>" method="post">
                                        <?= $block->getBlockHtml('formkey') ?>
                                        <button type="submit" class="action tocart primary">
                                            <span><?= /* @escapeNotVerified */ __('Add to Cart') ?></span>
                                        </button>
                                    </form>
                                <?php else: ?>
                                    <?php if ($item->getIsSalable()): ?>
                                        <div class="stock available"><span><?= /* @escapeNotVerified */ __('In stock') ?></span></div>
                                    <?php else: ?>
                                        <div class="stock unavailable"><span><?= /* @escapeNotVerified */ __('Out of stock') ?></span></div>
                                    <?php endif; ?>
                                <?php endif; ?>
                            </div>
                            <?php if ($this->helper('Magento\Wishlist\Helper\Data')->isAllow()) : ?>
                                <?php $wishlistUrl = $ampHelper->getUrlFromJson(
                                    'wishlist/index/add',
                                    $block->getAddToWishlistParams($item)
                                ); ?>
                                <div class="secondary-addto-links actions-secondary" data-role="add-to-links">
                                    <form method="post" action="<?= $wishlistUrl ?>">
                                        <button type="submit" title="<?= $block->escapeHtml(__('Add to Wish List')) ?>" class="action towishlist">
                                            <span><?= $block->escapeHtml(__('Add to Wish List')) ?></span>
                                        </button>
                                    </form>
                                </div>
                            <?php endif; ?>
                        </div>
                    </td>
                <?php endforeach; ?>
            </tr>
            </tbody>
            <tbody>
            <?php foreach ($block->getAttributes() as $attribute): ?>
                <?php $index = 0 ?>
                <tr>
                    <?php foreach ($block->getItems() as $item): ?>
                        <?php if ($index++ == 0): ?>
                            <th scope="row" class="cell label">
                                <span class="attribute label">
                                    <?= $block->escapeHtml($attribute->getStoreLabel() ? $attribute->getStoreLabel() : __($attribute->getFrontendLabel())) ?>
                                </span>
                            </th>
                        <?php endif; ?>
                        <td class="cell product attribute">
                            <div class="attribute value">
                                <?php switch ($attribute->getAttributeCode()) {
                                    case "price": ?>
                                        <?php
                                            /* @escapeNotVerified */ echo $block->getProductPrice(
                                                $item,
                                                '-compare-list-' . $attribute->getCode()
                                            )
                                        ?>
                                        <?php break;
                                    case "small_image": ?>
                                        <?php $block->getImage($item, 'product_small_image')->toHtml(); ?>
                                        <?php break;
                                    default: ?>
                                        <?php $value = $block->getProductAttributeValue($item, $attribute); ?>
                                        <?php if (is_string($value)) : ?>
                                            <?= /* @escapeNotVerified */ $helper->productAttribute($item, $value, $attribute->getAttributeCode()) ?>
                                        <?php else : ?>
                                            <?= (string) $value ?>
                                        <?php endif ?>
                                    <?php break;
                                } ?>
                            </div>
                        </td>
                    <?php endforeach; ?>
                </tr>
            <?php endforeach; ?>
            </tbody>
        </table>
    </div>
<?php else: ?>
    <div class="message info empty"><div><?= /* @escapeNotVerified */ __('You have no items to compare.') ?></div></div>
<?php endif; ?>
