<?php

use Magento\Framework\App\Action\Action;

$block->setMode('list');

// @codingStandardsIgnoreFile
?>
<?php
/**
 * @var $block \Swissup\Highlight\Block\Product\Abstract
 */
if ($exist = ($block->getProductCollection() && $block->getProductCollection()->getSize())) {
    $title = $block->getTitle();
    $items = $block->getProductCollection()->getItems();
    $_helper = $this->helper('Magento\Catalog\Helper\Output');
    $reviewType = \Magento\Catalog\Block\Product\ReviewRendererInterface::SHORT_VIEW;
}
?>

<?php if ($exist):?>
    <ol class="product-items">
        <?php $iterator = 1; ?>
        <?php foreach ($items as $_item): ?>
            <?php /* @escapeNotVerified */ echo($iterator++ == 1) ? '<li class="product-item">' : '</li><li class="product-item">' ?>
            <div class="product-item-info">
                <a class="product-item-photo" href="<?php /* @escapeNotVerified */ echo $_item->getProductUrl() ?>"
                   title="<?php /* @escapeNotVerified */ echo $block->stripTags($_item->getName(), null, true) ?>">
                    <?php echo $block->getImage($_item, 'side_column_widget_product_thumbnail')->toHtml(); ?>
                </a>
                <div class="product-item-details">
                    <strong class="product-item-name">
                        <a title="<?php echo $block->escapeHtml($_item->getName()) ?>"
                           href="<?php /* @escapeNotVerified */ echo $block->getProductUrl($_item) ?>"
                           class="product-item-link">
                            <?php echo $block->escapeHtml($_item->getName()) ?>
                        </a>
                    </strong>

                    <?php echo $block->getReviewsSummaryHtml($_item, $reviewType) ?>
                    <?php echo $block->getProductPriceHtml($_item, $this->getPriceSuffix()); ?>

                    <div class="product-item-actions">
                        <div class="actions-primary">
                            <?php if ($_item->isSaleable()): ?>
                                <?php $postParams = $block->getAddToCartPostParams($_item); ?>
                                <form data-role="tocart-form" data-product-sku="<?=  /* @NoEscape */ $_item->getSku() ?>" action="<?= /* @NoEscape */ $postParams['action'] ?>" method="post">
                                    <input type="hidden" name="product" value="<?= /* @escapeNotVerified */ $postParams['data']['product'] ?>">
                                    <input type="hidden" name="<?= /* @escapeNotVerified */ Action::PARAM_NAME_URL_ENCODED ?>" value="<?= /* @escapeNotVerified */ $postParams['data'][Action::PARAM_NAME_URL_ENCODED] ?>">
                                    <?= $block->getBlockHtml('formkey') ?>
                                    <button type="submit"
                                            title="<?= $block->escapeHtml(__('Add to Cart')) ?>"
                                            class="action tocart primary">
                                        <span><?= /* @escapeNotVerified */ __('Add to Cart') ?></span>
                                    </button>
                                </form>
                            <?php else: ?>
                                <?php if ($_item->getIsSalable()): ?>
                                    <div class="stock available" title="<?php /* @escapeNotVerified */ echo __('Availability') ?>">
                                        <span><?php /* @escapeNotVerified */ echo __('In stock') ?></span>
                                    </div>
                                <?php else: ?>
                                    <div class="stock unavailable" title="<?php /* @escapeNotVerified */ echo __('Availability') ?>">
                                        <span><?php /* @escapeNotVerified */ echo __('Out of stock') ?></span>
                                    </div>
                                <?php endif; ?>
                            <?php endif; ?>
                        </div>
                    </div>
                </div>
            </div>
            <?php echo($iterator == count($items)+1) ? '</li>' : '' ?>
        <?php endforeach ?>
    </ol>
    <?php if (!$block->isRedirectToCartEnabled()) : ?>
        <script type="text/x-magento-init" data-init-lazy="submit">
        {
            "[data-role=tocart-form], .form.map.checkout": {
                "catalogAddToCart": {
                    "product_sku": "<?= $block->escapeJs($_item->getSku()) ?>"
                }
            }
        }
        </script>
    <?php endif; ?>
<?php endif;?>
