<?php
    $isCategory = $block->getRequest()->getParam('mode') == 'category';
?>
<div style="width: <?= $isCategory ? '42px' : '62px' ?>; height: <?= $isCategory ? '60px' : '94px' ?>; border-radius: 10px; background: var(--hexagon-background)">

<div style="color: var(--icon-color); font-size: var(--icon-size); width: <?= $isCategory ? '36px' : '56px' ?>; height: <?= $isCategory ? '36px' : '56px' ?>; position: absolute; background: #fff; z-index: 10; border-radius: 50%; top: 0; left: 0; right: 0; bottom: 0; margin: auto"> <i class="<?= $block->getFaIcon() ?>" style="margin-top: <?= $isCategory ? '3px' : '6px' ?>;"></i></div>

<div style="position: absolute; border-radius: <?= $isCategory ? '2px' : '4px' ?>; padding: <?= $isCategory ? '4px 5px 1px' : '5px 5px 3px' ?>; z-index: 11; top: 67%; min-width: <?= $isCategory ? '60px' : '94px' ?>; left: 50%; transform: translateX(-50%); box-shadow: 0 1px 2px rgba(0, 0, 0, 0.27); text-shadow: 0 2px 2px rgba(0, 0, 0, 0.1); background: var(--ribbon-background); color: var(--ribbon-color); box-sizing: content-box"><?= $this->helper(\Swissup\ProLabels\Helper\Preset::class)->getLabelText(); ?></div>

<b style="position: absolute; border-radius: inherit; background: inherit; top: 0; left: 0; right: 0; bottom: 0; transform: rotate(60deg)"></b>
<b style="position: absolute; border-radius: inherit; background: inherit; top: 0; left: 0; right: 0; bottom: 0; transform: rotate(-60deg)"></b>

</div>
