<?php

namespace Swissup\SoldTogether\Model;

use Magento\Framework\Api\SearchCriteriaBuilder;
use Magento\Sales\Api\OrderRepositoryInterface;
use Swissup\SoldTogether\Model\Resolver\ResourceModels as ResourceResolver;
use Swissup\SoldTogether\Observer\Cron as CronProcessor;
use Magento\Framework\App\Config\ScopeConfigInterface;
use Magento\Store\Model\ScopeInterface;

abstract class AbstractIndexer
{
    const XML_PATH_ORDER_DAY_LIMIT = 'soldtogether/relations/order_not_older_than_x_days';

    /**
     * @var ResourceResolver
     */
    protected $resourceResolver;

    /**
     * @var OrderRepositoryInterface
     */
    protected $orderRepository;

    /**
     * @var SearchCriteriaBuilder
     */
    protected $searchCriteriaBuilder;

    /**
     * @var CronProcessor
     */
    protected $cronProcessor;

    /**
     * @var ScopeConfigInterface
     */
    private $scopeConfig;

    /**
     * @var string
     */
    protected $linkType = '';

    /**
     * @param ResourceResolver         $resourceResolver
     * @param OrderRepositoryInterface $orderRepository
     * @param SearchCriteriaBuilder    $searchCriteriaBuilder
     * @param CronProcessor            $cronProcessor
     * @param ScopeConfigInterface     $scopeConfig
     */
    public function __construct(
        ResourceResolver $resourceResolver,
        OrderRepositoryInterface $orderRepository,
        SearchCriteriaBuilder $searchCriteriaBuilder,
        CronProcessor $cronProcessor,
        ScopeConfigInterface $scopeConfig
    ) {
        $this->resourceResolver = $resourceResolver;
        $this->orderRepository = $orderRepository;
        $this->searchCriteriaBuilder = $searchCriteriaBuilder;
        $this->cronProcessor = $cronProcessor;
        $this->scopeConfig = $scopeConfig;
    }

    public function reindex($pageNumber, $pageSize)
    {
        $criteria = $this->getSearchCriteria($pageNumber, $pageSize);
        $ordersList = $this->orderRepository->getList($criteria);
        $links = [];
        foreach ($ordersList->getItems() as $order) {
            $this->collectLinks($order, $links);
        }

        if ($links) {
            $resource = $this->resourceResolver->get($this->linkType);
            if ($resource) {
                $resource->updateLinkedData($links);
            }
        }
    }

    abstract protected function collectLinks($order, array &$links);

    /**
     * Delete autogenerated relations
     */
    public function deleteAutogeneratedRelations()
    {
        $resource = $this->resourceResolver->get($this->linkType);
        if ($resource) {
            $resource->deleteAutogeneratedRelations();
        }
    }

    /**
     * {@inheritdoc}
     */
    public function getItemsToProcessCount()
    {
        $criteria = $this->getSearchCriteria(1, 1);
        $ordersList = $this->orderRepository->getList($criteria);

        return $ordersList->getSize();
    }

    /**
     * @param $pageNumber
     * @param $pageSize
     * @return \Magento\Framework\Api\SearchCriteria
     */
    private function getSearchCriteria($pageNumber, $pageSize)
    {
        $dayLimit = (int) $this->scopeConfig->getValue(
            self::XML_PATH_ORDER_DAY_LIMIT,
            ScopeInterface::SCOPE_STORE
        );
        $createdAtFrom = date('Y-m-d h:i:s', strtotime("-{$dayLimit} day"));
        $criteria = $this->searchCriteriaBuilder
            ->addFilter('created_at', $createdAtFrom, 'gteq')
            ->setPageSize($pageSize)
            ->setCurrentPage($pageNumber)
            ->create();

        return $criteria;
    }
}
