<?php

    // @codingStandardsIgnoreFile

    /** @var $block \Magento\Catalog\Block\Adminhtml\Product\Helper\Form\Gallery\Content */
    $elementName = $block->getElement()->getName() . '[images]';
    $formName = $block->getFormName();

    $slideId = $block->getRequest()->getParam('slider_id');
    $galleryHelper = $this->helper(\Swissup\EasySlide\Helper\Gallery::class);
    $galleryData = $galleryHelper->getData($slideId);
    $datepickerConfig = $galleryHelper->getDatepickerConfig();
    $galleryConfig = [
        'template' => "#{$block->getHtmlId()}-template",
        'formatter' => [
            'storeTimeZone' => $datepickerConfig['storeTimeZone'],
            'dateFormat' => $datepickerConfig['options']['dateFormat'],
            'timeFormat' => $datepickerConfig['options']['timeFormat'],
        ]
    ];

    $jsonHelper = $this->helper('Magento\Framework\Json\Helper\Data');
?>
<div id="<?= $block->getHtmlId() ?>"
     class="gallery"
     data-mage-init='{"Swissup_EasySlide/js/slide-gallery": <?= json_encode($galleryConfig) ?>}'
     data-parent-component="<?= $block->escapeHtml($block->getData('config/parentComponent')) ?>"
     data-images="<?= $block->escapeHtml(
        $jsonHelper->jsonEncode($galleryData)
    ) ?>"
     data-types="<?= $block->escapeHtml(
        $jsonHelper->jsonEncode($block->getImageTypes())
     ) ?>"
    >
    <?php if (!$block->getElement()->getReadonly()) {?>
        <div class="image image-placeholder">
            <details class="slide-gallery--other-types actions-split">
                <summary title="<?= __('Other types') ?>"></summary>
                <ul class="dropdown-menu">
                    <li data-action="newSlideImage">
                        <span class="item"><?= __('Image') ?></span>
                    </li>
                    <li data-action="newSlideHTML">
                        <span class="item"><?= __('Raw HTML') ?></span>
                    </li>
                </ul>
            </details>
            <?= $block->getUploaderHtml(); ?>
            <div class="product-image-wrapper">
                <p class="image-placeholder-text">
                    <?= __('Browse to find or drag image here') ?>
                </p>
            </div>
        </div>
    <?php } ?>
    <?php foreach ($block->getImageTypes() as $typeData) {
    ?>
        <input name="<?= $block->escapeHtml($typeData['name']) ?>"
               data-form-part="<?= $formName ?>"
               class="image-<?= $block->escapeHtml($typeData['code']) ?>"
               type="hidden"
               value="<?= $block->escapeHtml($typeData['value']) ?>"/>
    <?php

} ?>

    <script id="<?= $block->getHtmlId() ?>-template" type="text/x-magento-template">
        <?= $block->fetchView($block->getTemplateFile('helper/gallery/template-image.phtml')) ?>
    </script>

    <script data-role="img-dialog-container-tmpl" type="text/x-magento-template">
        <?= $block->fetchView($block->getTemplateFile('helper/gallery/template-dialog-container.phtml')) ?>
    </script>

    <script data-role="img-dialog-tmpl" type="text/x-magento-template">
        <?= $block->fetchView($block->getTemplateFile('helper/gallery/template-dialog-content.phtml')) ?>
    </script>
</div>

<script>
    function byteConvert (bytes) {
        if (isNaN(bytes)) {
            return '';
        }
        var symbols = ['bytes', 'KB', 'MB', 'GB', 'TB', 'PB', 'EB', 'ZB', 'YB'];
        var exp = Math.floor(Math.log(bytes)/Math.log(2));
        if (exp < 1) {
            exp = 0;
        }
        var i = Math.floor(exp / 10);
        bytes = bytes / Math.pow(2, 10 * i);
        if (bytes.toString().length > bytes.toFixed(2).toString().length) {
            bytes = bytes.toFixed(2);
        }
        return bytes + ' ' + symbols[i];
    };

    jQuery('body').trigger('contentUpdated');
</script>
